# Generated by Django 4.1.4 on 2022-12-22 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messagesApi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="HasBeenRead",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="message",
            name="creationDate",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
